apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: user/consumer:latest
        ports:
        - containerPort: 80
        - containerPort: 1235
        resources:
          requests:
            cpu: "500m"
