apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: user/producer:latest
        ports:
        - containerPort: 80
        - containerPort: 1234
        resources:
          requests:
            cpu: "500m"
